orbs:
  gradle: circleci/gradle@x.y
version: 2.1
workflows:
  ophen-workflow:
    jobs:
      - gradle/test
        store_artifacts: build/reports/
        test_command: OhpenTests
        test_results_path: build/test-results/cucumber-html-report.html/