orbs:
  gradle: circleci/gradle@2.2.0
version: 2.1
workflows:
  ophen-workflow:
    jobs:
      - gradle/check:
          context:
            - Ohpen
          test_results_path: build/test-results/cucumber-html-report.html/